### ISSUE TITLE
Make CBB check more specific

### ISSUE THREAD

**Issue by iadgovuser1** [nsacyber/Windows-Secure-Host-Baseline#11]
For STIG ID WN10-00-000040/Vuln ID  V-63349, check CurrentBuild >=14393 and UBR >= 447 for CBB rather than only checking ReleaseID is 1607.

**Comment by Prowler2** [comment]
Be advised that the UBR registry key changes with every patch applied to the OS.  CBB now includes all three builds of windows 10 (1507, 1511, 1607)
https://support.microsoft.com/en-us/help/4000825/windows-10-and-windows-server-2016-update-history
https://technet.microsoft.com/en-us/windows/mt679505.aspx?ocid=wc-ext-aka

**Comment by iadgovuser1** [comment]
Yep, but we can change our audit files to match fairly quickly.
