### ISSUE TITLE
Acrobat Reader Administrative Template error

### ISSUE THREAD

**Issue by Prowler2** [nsacyber/Windows-Secure-Host-Baseline#25]
In the ReaderDC.admx administrative template line 273 there is an error that creates the DWORD value "bAdobeSendPluginToggle" in key "cServices" instead of key "cCloud".  

Ref Adobe Acrobat DC Continuous Track STIG V1R2 ID V-64937 - Using the Registry Editor, Navigate to the following HKEY_LOCAL_MACHINE\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown\cCloud    
Value Name: bAdobeSendPluginToggle
Type: REG_DWORD
Value: 0

**Comment by iadgovuser1** [comment]
I'm going through the Adobe Reader DC templates and policies right now so I will check in this fix with the other fixes hopefully by the end of the week. Thanks for reporting this.

**Comment by iadgovuser1** [comment]
It is cCloud according to https://www.adobe.com/devnet-docs/acrobatetk/tools/PrefRef/Windows/Workflows.html?zoom_highlight=bAdobeSendPluginToggle#idkeyname_1_25390
