### ISSUE TITLE
 Property setting is supported only on core types

### ISSUE THREAD

**Issue by skyg0** [nsacyber/Windows-Secure-Host-Baseline#61]
After running command for SHB policy on standalone system: 

Invoke-ApplySecureHostBaseline : Cannot validate argument on parameter 'Path'. Cannot invoke method. Method invocation is supported only on core types in this language mode.

$ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage

I didn't enable Constrained Language, running PS as Admin on Admin User. 

How can I disable? 

Thank you.

**Comment by skyg0** [comment]
Create new admin user solves issue.

**Comment by iadgovuser1** [comment]
@skyg0 If you applied the AppLocker policy (when not in audit mode), then PowerShell would be in Constrained Language mode. That's one possibility.
