### ISSUE TITLE
"Hardware" link is offline

### ISSUE THREAD

**Issue by beerisgood** [nsacyber/Windows-Secure-Host-Baseline#63]
The following link from https://github.com/nsacyber/Windows-Secure-Host-Baseline/blob/master/Windows/README.md is offline: https://github.com/nsacyber/Windows-Secure-Host-Baseline/blob/master/Hardware/README.md

**Comment by iadgovuser1** [comment]
The hardware page was removed on purpose (See #59 for the commit). The individual DoD service components and OEMs put together their own hardware lists (not publicly available) and didn't contribute to this repository so the hardware section was removed. I will fix the main readme to remove the link. If you want to see the old content, then you can see the repo at the point with this link: https://github.com/nsacyber/Windows-Secure-Host-Baseline/tree/c59f2145c7efe8d4a966f065cf229300ce542e03
